#include <pebble.h>

// Resource and Settings Keys
#define SETTINGS_KEY 1
#define COL_COUNT 14
#define ROW_COUNT 10
#define CIPHER_LEN 44

// AppMessage Keys (Matching your Alloy/Pebble JS keys)
#define MESSAGE_KEY_BackgroundColor 0
#define MESSAGE_KEY_TextColor       1
#define MESSAGE_KEY_HourFormat      2

static Window *s_main_window;
static Layer *s_canvas_layer;
static GFont s_encryption_font;

// The "Encrypted" character set
static const char *CIPHER_CHARS = "abcdefg&ur#+$zksdzkjsdtcnuqplynvi&+r*$i*#@*c#";

// 6x10 bitmap for digits 0-9
static const uint8_t DIGITS[10][60] = {
    {0,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0}, // 0
    {0,0,1,1,0,0,0,1,1,1,0,0,1,1,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,1,1,1,1,1}, // 1
    {0,1,1,1,1,0,1,1,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,1,1,1,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,1,1}, // 2
    {0,1,1,1,1,0,1,1,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,1,1,1,1,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0}, // 3
    {0,0,0,1,1,0,0,0,1,1,1,0,0,1,1,1,1,0,1,1,0,1,1,0,1,1,0,1,1,0,1,1,1,1,1,1,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0}, // 4
    {1,1,1,1,1,1,1,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,1,0,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0}, // 5
    {0,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,0,0,1,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0}, // 6
    {1,1,1,1,1,1,1,1,0,0,1,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0,0,1,1,0,0,0}, // 7
    {0,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0}, // 8
    {0,1,1,1,1,0,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,1,0,0,0,0,1,1,0,0,0,0,1,1,1,1,0,0,1,1,0,1,1,1,1,0}  // 9
};

typedef struct {
  GColor backgroundColor;
  GColor textColor;
  bool use24Hour;
} __attribute__((__packed__)) AppSettings;

static AppSettings settings;

// Helper to draw a pair of digits (Hours or Minutes)
static void draw_encrypted_block(GContext *ctx, int d1, int d2, int start_y, int start_x, int cw) {
  for (int r = 0; r < ROW_COUNT; r++) {
    for (int c = 0; c < COL_COUNT; c++) {
      bool active = false;
      if (c < 6) active = DIGITS[d1][r * 6 + c];
      else if (c >= 8) active = DIGITS[d2][r * 6 + (c - 8)];

      if (active) {
        char buf[2] = { CIPHER_CHARS[rand() % CIPHER_LEN], '\0' };
        // We draw individual characters to maintain the "glitchy" matrix look
        graphics_draw_text(ctx, buf, s_encryption_font,
                           GRect(start_x + (c * cw), start_y + (r * 8), cw + 2, 12),
                           GTextOverflowModeWordWrap, GTextAlignmentCenter, NULL);
      }
    }
  }
}

static void update_proc(Layer *layer, GContext *ctx) {
  time_t temp = time(NULL);
  struct tm *t = localtime(&temp);

  // 1. Draw Background
  graphics_context_set_fill_color(ctx, settings.backgroundColor);
  graphics_fill_rect(ctx, layer_get_bounds(layer), 0, GCornerNone);

  // 2. Prepare Time
  int hours = t->tm_hour;
  if (!settings.use24Hour) {
    hours = hours % 12;
    if (hours == 0) hours = 12;
  }

  // 3. Draw Text
  graphics_context_set_text_color(ctx, settings.textColor);

  int char_width = 9;
  int start_x = (layer_get_bounds(layer).size.w - (COL_COUNT * char_width)) / 2;

  // Draw Hours (top block)
  draw_encrypted_block(ctx, hours / 10, hours % 10, 1, start_x, char_width);
  // Draw Minutes (bottom block)
  draw_encrypted_block(ctx, t->tm_min / 10, t->tm_min % 10, 85, start_x, char_width);
}

static void inbox_received_handler(DictionaryIterator *iter, void *context) {
  // Use the constants generated by the Pebble SDK from package.json
  Tuple *bg_t = dict_find(iter, MESSAGE_KEY_BackgroundColor);
  if (bg_t) {
    settings.backgroundColor = GColorFromHEX(bg_t->value->int32);
    APP_LOG(APP_LOG_LEVEL_DEBUG, "Background Color updated");
  }

  Tuple *tx_t = dict_find(iter, MESSAGE_KEY_TextColor);
  if (tx_t) {
    settings.textColor = GColorFromHEX(tx_t->value->int32);
    APP_LOG(APP_LOG_LEVEL_DEBUG, "Text Color updated");
  }

  Tuple *fmt_t = dict_find(iter, MESSAGE_KEY_HourFormat);
  if (fmt_t) {
    settings.use24Hour = (fmt_t->value->int32 == 1);
  }

  // Save to persistent storage and trigger a redraw
  persist_write_data(SETTINGS_KEY, &settings, sizeof(settings));
  layer_mark_dirty(s_canvas_layer);
}

static void handle_minute_tick(struct tm *tick_time, TimeUnits units_changed) {
  layer_mark_dirty(s_canvas_layer);
}

static void window_load(Window *window) {
  Layer *window_layer = window_get_root_layer(window);
  GRect bounds = layer_get_bounds(window_layer);

  s_canvas_layer = layer_create(bounds);
  layer_set_update_proc(s_canvas_layer, update_proc);
  layer_add_child(window_layer, s_canvas_layer);

  // Load custom font from resources
  s_encryption_font = fonts_load_custom_font(resource_get_handle(RESOURCE_ID_FONT_ENCRYPTION_8));
}

static void window_unload(Window *window) {
  layer_destroy(s_canvas_layer);
  fonts_unload_custom_font(s_encryption_font);
}

static void init() {
  // Load Default Settings
  settings.backgroundColor = GColorOxfordBlue;
  settings.textColor = GColorWhite;
  settings.use24Hour = true;
  persist_read_data(SETTINGS_KEY, &settings, sizeof(settings));

  s_main_window = window_create();
  window_set_window_handlers(s_main_window, (WindowHandlers) {
    .load = window_load,
    .unload = window_unload,
  });
  window_stack_push(s_main_window, true);

  // Subscribe to time
  tick_timer_service_subscribe(MINUTE_UNIT, handle_minute_tick);

  // Subscribe to settings changes
  app_message_register_inbox_received(inbox_received_handler);
  app_message_open(128, 128);
}

static void deinit() {
  window_destroy(s_main_window);
}

int main(void) {
  init();
  app_event_loop();
  deinit();
}